# This file was generated by GoReleaser. DO NOT EDIT.
cask "tidewake" do
  version "0.1.0-rc2"

  on_macos do
    on_arm do
      sha256 "d9b78df0b3e450a38e10ef6376ea475d7147c2601e70ab1e10849502f1ddbb88"
      url "https://github.com/berkkorkmaz/tidewake/releases/download/v#{version}/tidewake_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cec3b79be7cf643be8c0bde2c13dc0de658b766c16f79323336397cf30cb908a"
      url "https://github.com/berkkorkmaz/tidewake/releases/download/v#{version}/tidewake_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "tidewake"
  desc "Find what Claude Code and Codex sessions left behind"
  homepage "https://github.com/berkkorkmaz/tidewake"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tidewake"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tidewake"]
    end
  end

  # No zap stanza required
end
