# This file was generated by GoReleaser. DO NOT EDIT.
cask "tidewake" do
  version "0.1.0-rc5"

  on_macos do
    on_arm do
      sha256 "ccd152f9ab2afb124b33989bd957ae274164c5a0302db1525a741b076e1d5d27"
      url "https://github.com/berkkorkmaz/tidewake/releases/download/v#{version}/tidewake_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d68fc7cd794ddb05ec5f9db07d5501b835b661f9882ea57f9daf23e827dbce85"
      url "https://github.com/berkkorkmaz/tidewake/releases/download/v#{version}/tidewake_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "148062b11ab600fa7e05a4fa1a0b96811b23c47aa41ac8bfe86c0caa96141f29"
      url "https://github.com/berkkorkmaz/tidewake/releases/download/v#{version}/tidewake_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "366d46c01a97098d74c5f06fd4c4b39921491f79cad8ea33fa6b790285513235"
      url "https://github.com/berkkorkmaz/tidewake/releases/download/v#{version}/tidewake_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tidewake"
  desc "Find what Claude Code and Codex sessions left behind"
  homepage "https://github.com/berkkorkmaz/tidewake"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tidewake"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tidewake"]
    end
  end

  # No zap stanza required
end
