# This file was generated by GoReleaser. DO NOT EDIT.
cask "tidewake" do
  version "0.1.0-rc3"

  on_macos do
    on_arm do
      sha256 "d05b6712a80bef156fc123c74b6752b10751b53d271fec2d46acdfae20c9a3ce"
      url "https://github.com/berkkorkmaz/tidewake/releases/download/v#{version}/tidewake_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0be299132e4fb891594bee3840d15a1f354f0b49cf0b5455338ce3fb743603f3"
      url "https://github.com/berkkorkmaz/tidewake/releases/download/v#{version}/tidewake_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "tidewake"
  desc "Find what Claude Code and Codex sessions left behind"
  homepage "https://github.com/berkkorkmaz/tidewake"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tidewake"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tidewake"]
    end
  end

  # No zap stanza required
end
